line-length = 88

target-version = "py312"

exclude = [
    ".git",
    "__pycache__",
    ".ruff_cache",
    "alembic",
    "venv",
    ".venv",
    "build",
    "dist",
]

[lint]
extend-select = [
    "ARG",  # flake8-unused-arguments
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "EM",   # flake8-errmsg
    "EXE",  # flake8-executable
    "FURB", # refurb
    "G",    # flake8-logging-format
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "NPY",  # NumPy specific rules
    "PD",   # pandas-vet
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PL",   # pylint
    "PT",   # flake8-pytest-style
    "PTH",  # flake8-use-pathlib
    "PYI",  # flake8-pyi
    "RET",  # flake8-return
    "RUF",  # Ruff-specific
    "SIM",  # flake8-simplify
    "T20",  # flake8-print
    "UP",   # pyupgrade
    "YTT",  # flake8-2020
]

ignore = [
    "ISC001",  # Conflicts with formatter
    "PLR09",   # Too many <...>
    "PLR2004", # Magic value used in comparison
]

[lint.isort]
known-first-party = ["core", "dashboard"]

[lint.mccabe]
max-complexity = 10

[lint.per-file-ignores]
"**/config.py" = ["N806"]
"tests/**" = ["D"]
"__init__.py" = ["F401", "E402"]
