name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

permissions:
  contents: read

jobs:
  checks:
      name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
      runs-on: ${{ matrix.runs-on }}
      strategy:
        fail-fast: false
        matrix:
          python-version: ["3.12", "3.13"]
          runs-on: [ubuntu-latest, windows-latest, macos-latest]

          include:
            - python-version: pypy-3.12
              runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install PyAudio dependencies (Ubuntu)
          if: runner.os == 'Linux'
          run: |
            sudo apt-get update
            sudo apt-get install -y python3-pyaudio portaudio19-dev

        - name: Install PyAudio dependencies (macOS)
          if: runner.os == 'macOS'
          run: |
            brew install portaudio

        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            allow-prereleases: true

        - name: Setup uv
          uses: astral-sh/setup-uv@v5

        - name: Install nox
          run: uv tool install nox

        - name: Test hatch
          run: |
            nox -s 'tests' -- --hatch=True --vcs=False
            nox -s 'tests' -- --hatch=True --vcs=True


  nox:
    name: Check included Noxfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PyAudio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyaudio portaudio19-dev

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          allow-prereleases: true

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install nox
        run: uv tool install nox

      - name: Test hatch
        run: |
          nox -s 'tests' -- --hatch=True --vcs=False
          nox -s 'tests' -- --hatch=True --vcs=True

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: tox-dev/action-pre-commit-uv@v1

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install PyAudio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyaudio portaudio19-dev

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: hynek/setup-cached-uv@v2

      - name: Run tests with tox
        run: |
          uvx tox -e py-${{ matrix.python-version }} -- --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.12'
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
