name: Python CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  FORCE_COLOR: 1
  UV_CACHE_DIR: /tmp/.uv-cache
permissions:
  contents: read
jobs:
  checks:
    name: Check Python 3.12 on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache PyAudio dependencies (Ubuntu)
        if: runner.os == 'Linux'
        uses: actions/cache@v4
        with:
          path: ~/.apt-cache
          key: ${{ runner.os }}-apt-pyaudio-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-pyaudio-

      - name: Install PyAudio dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyaudio portaudio19-dev

      # macOS specific steps
      - name: Cache Homebrew packages
        if: runner.os == 'macOS'
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-brew-pyaudio-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-brew-pyaudio-

      - name: Install PyAudio dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install portaudio

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          allow-prereleases: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install nox
        run: uv tool install nox

      - name: Activate .venv (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "Activating virtual environment on Windows"
          .\.venv\Scripts\activate

      - name: Activate .venv (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "Activating virtual environment on Linux/macOS"
          source .venv/bin/activate

      - name: Run hatch tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          nox -s 'tests' -- --hatch=True --vcs=False
          nox -s 'tests' -- --hatch=True --vcs=True

      - name: Run hatch tests (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          nox -s 'tests' -- --hatch=True --vcs=False
          nox -s 'tests' -- --hatch=True --vcs=True

      - name: Minimize uv cache
        run: uv cache prune --ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Activate .venv
        shell: bash
        run: |
          source .venv/bin/activate

      - uses: tox-dev/action-pre-commit-uv@v1

      - name: Minimize uv cache
        run: uv cache prune --ci

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache PyAudio dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install PyAudio dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pyaudio portaudio19-dev

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Activate .venv
        shell: bash
        run: |
          source .venv/bin/activate

      - name: Run tests with tox
        run: >
          uvx tox -e py-3.12 -- --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Minimize uv cache
        run: uv cache prune --ci
